# Generated by Django 4.2.9 on 2024-01-29 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, verbose_name='Name_Event')),
                ('description', models.CharField(max_length=600, verbose_name='Description_Event')),
                ('date_event', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Create')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_of_reservs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_person_booking', models.CharField(max_length=450, verbose_name='Name_Person')),
                ('reservation_date', models.DateField()),
                ('state', models.CharField(choices=[('activ', 'Active'), ('canceled', 'Canceled')], default='activ', max_length=10, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Create')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.events')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=450, verbose_name='Name_Places')),
                ('locations_available', models.IntegerField(verbose_name='Locations Available')),
                ('address', models.CharField(max_length=450, verbose_name='Address')),
                ('telphone', models.CharField(max_length=250, verbose_name='Telphone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Create')),
                ('id_gestion_of_reserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.gestion_of_reservs')),
            ],
        ),
        migrations.AddField(
            model_name='gestion_of_reservs',
            name='id_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.places'),
        ),
        migrations.AddField(
            model_name='events',
            name='id_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.places'),
        ),
        migrations.CreateModel(
            name='Event_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_description', models.CharField(max_length=600, verbose_name='Description_Comment')),
                ('event_calification', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Event Calification')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Create')),
                ('id_gestion_of_reserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.gestion_of_reservs')),
            ],
        ),
    ]
