# Generated by Django 4.2.9 on 2024-01-29 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apisReserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('state', models.CharField(choices=[('activ', 'Active'), ('canceled', 'Canceled')], default='activ', max_length=10, verbose_name='State')),
                ('places_reserv', models.IntegerField(default=0, help_text='Number of places reserv', verbose_name='Number_of_places_reserv')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of Create')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Date of Modified')),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='id_gestion_of_reserv',
        ),
        migrations.RemoveField(
            model_name='event_comments',
            name='id_gestion_of_reserv',
        ),
        migrations.RemoveField(
            model_name='events',
            name='id_place',
        ),
        migrations.AddField(
            model_name='event_comments',
            name='id_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apisReserve.events', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='event_comments',
            name='id_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='event_comments',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of Modified'),
        ),
        migrations.AddField(
            model_name='events',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='number_of_places',
            field=models.IntegerField(default=0, help_text='Total number of available seats', verbose_name='Number_of_places'),
        ),
        migrations.AddField(
            model_name='events',
            name='number_of_places_reserv',
            field=models.IntegerField(default=0, help_text='Number of seats currently reserved', verbose_name='Number_of_places_reserv'),
        ),
        migrations.DeleteModel(
            name='Gestion_of_reservs',
        ),
        migrations.DeleteModel(
            name='Places',
        ),
        migrations.AddField(
            model_name='reservs',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisReserve.events', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='reservs',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
