# Generated by Django 4.2.9 on 2024-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisReserve', '0004_rename_id_event_event_comments_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number_of_places_available',
            field=models.IntegerField(default=0, help_text='Number of seats currently reserved', verbose_name='Number_of_places_available'),
        ),
    ]
