# Generated by Django 4.2.9 on 2024-01-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisReserve', '0005_alter_events_number_of_places_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservs',
            name='reservation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
