# Generated by Django 4.2.9 on 2024-01-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisReserve', '0006_alter_reservs_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Event Image'),
        ),
    ]
