# Generated by Django 4.2.9 on 2024-02-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisReserve', '0008_remove_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservs',
            name='state',
            field=models.CharField(choices=[('activa', 'Active'), ('cancelada', 'Canceled')], default='activ', max_length=10, verbose_name='State'),
        ),
    ]
